#!/usr/bin/env bash

append_to_zshrc 'export HOMEBREW_CASK_OPTS="--appdir=/Applications"'
export HOMEBREW_CASK_OPTS="--appdir=/Applications"

brew install caskroom/cask/brew-cask
brew cask install adobe-reader
brew cask install alfred
brew cask install android-file-transfer
brew cask install atom
brew cask install coconutbattery
brew cask install disk-inventory-x
brew cask install dropbox
brew cask install flux
brew cask install google-chrome --caskroom=/Applications
brew cask install google-drive
brew cask install handbrake
brew cask install imagealpha
brew cask install imageoptim
brew cask install iterm2
brew cask install macdown
brew cask install mactracker
brew cask install mailbox
brew cask install rescuetime
brew cask install rubymine
brew cask install spotify
brew cask install skype
brew cask install sublime-text
brew cask install sourcetree
brew cask install teamviewer
brew cask install tomighty
brew cask install virtualbox
brew cask install vagrant
brew cask install wechat
brew cask install vlc
brew cask install vmware-fusion
